.TH "OpenGLAssignment::Model" 3 "Sun May 24 2020" "Jesús Fermín Villar Ramírez | OpenGLAssignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenGLAssignment::Model
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Model\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModel\fP (\fBModel\fP *parent=nullptr)"
.br
.RI "Creates an instance\&. "
.ti -1c
.RI "\fBModel\fP (std::shared_ptr< \fBMesh\fP > mesh, std::shared_ptr< \fBMaterial\fP > material, \fBModel\fP *parent=nullptr)"
.br
.RI "Creates an instance\&. "
.ti -1c
.RI "glm::mat4 \fBget_transform\fP ()"
.br
.RI "Get the transformation matrix of the model\&. "
.ti -1c
.RI "void \fBset_transform\fP (glm::mat4 transform)"
.br
.RI "Set the transformation matrix of the model\&. "
.ti -1c
.RI "void \fBset_material\fP (std::shared_ptr< \fBMaterial\fP > mat)"
.br
.RI "Set the material of the model\&. "
.ti -1c
.RI "void \fBset_mesh\fP (std::shared_ptr< \fBMesh\fP > mesh)"
.br
.RI "Set the mesh of the model\&. "
.ti -1c
.RI "void \fBrender\fP (\fBCamera\fP *camera)"
.br
.RI "Render the model\&. "
.ti -1c
.RI "glm::vec3 \fBget_position\fP ()"
.br
.RI "Get the position of the model\&. "
.ti -1c
.RI "std::shared_ptr< \fBMaterial\fP > \fBget_material\fP ()"
.br
.RI "Get the material of the model\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file Model\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OpenGLAssignment::Model::Model (\fBModel\fP * parent = \fCnullptr\fP)\fC [inline]\fP"

.PP
Creates an instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIparent\fP The parent 
.RE
.PP

.PP
Definition at line 58 of file Model\&.hpp\&.
.SS "OpenGLAssignment::Model::Model (std::shared_ptr< \fBMesh\fP > mesh, std::shared_ptr< \fBMaterial\fP > material, \fBModel\fP * parent = \fCnullptr\fP)\fC [inline]\fP"

.PP
Creates an instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImesh\fP The mesh of the model 
.br
\fImaterial\fP The material of the model 
.br
\fIparent\fP the parent of the model 
.RE
.PP

.PP
Definition at line 69 of file Model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr<\fBMaterial\fP> OpenGLAssignment::Model::get_material ()\fC [inline]\fP"

.PP
Get the material of the model\&. 
.PP
\fBReturns\fP
.RS 4
The material of the model 
.RE
.PP

.PP
Definition at line 154 of file Model\&.hpp\&.
.SS "glm::vec3 OpenGLAssignment::Model::get_position ()\fC [inline]\fP"

.PP
Get the position of the model\&. 
.PP
\fBReturns\fP
.RS 4
The position of the model 
.RE
.PP

.PP
Definition at line 145 of file Model\&.hpp\&.
.SS "glm::mat4 OpenGLAssignment::Model::get_transform ()\fC [inline]\fP"

.PP
Get the transformation matrix of the model\&. 
.PP
\fBReturns\fP
.RS 4
The transformation matrix 
.RE
.PP

.PP
Definition at line 83 of file Model\&.hpp\&.
.SS "void OpenGLAssignment::Model::render (\fBCamera\fP * camera)\fC [inline]\fP"

.PP
Render the model\&. 
.PP
\fBParameters\fP
.RS 4
\fIcamera\fP A reference to the scene camera 
.RE
.PP

.PP
Definition at line 120 of file Model\&.hpp\&.
.SS "void OpenGLAssignment::Model::set_material (std::shared_ptr< \fBMaterial\fP > mat)\fC [inline]\fP"

.PP
Set the material of the model\&. 
.PP
\fBParameters\fP
.RS 4
\fImat\fP The material to set 
.RE
.PP

.PP
Definition at line 102 of file Model\&.hpp\&.
.SS "void OpenGLAssignment::Model::set_mesh (std::shared_ptr< \fBMesh\fP > mesh)\fC [inline]\fP"

.PP
Set the mesh of the model\&. 
.PP
\fBParameters\fP
.RS 4
\fImesh\fP The mesh of the model 
.RE
.PP

.PP
Definition at line 111 of file Model\&.hpp\&.
.SS "void OpenGLAssignment::Model::set_transform (glm::mat4 transform)\fC [inline]\fP"

.PP
Set the transformation matrix of the model\&. 
.PP
\fBParameters\fP
.RS 4
\fItransform\fP The transformation matrix to set 
.RE
.PP

.PP
Definition at line 93 of file Model\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Jesús Fermín Villar Ramírez | OpenGLAssignment from the source code\&.
