.TH "OpenGLAssignment::Scene" 3 "Sun May 24 2020" "Jesús Fermín Villar Ramírez | OpenGLAssignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenGLAssignment::Scene
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP (std::string name, unsigned int width, unsigned int height)"
.br
.RI "Creates an instance\&. "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "\fBScene\fP loop\&. "
.ti -1c
.RI "void \fBrender\fP ()"
.br
.RI "Render the scene\&. "
.ti -1c
.RI "void \fBinput\fP ()"
.br
.RI "Handle the input\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file Scene\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OpenGLAssignment::Scene::Scene (std::string name, unsigned int width, unsigned int height)\fC [inline]\fP"

.PP
Creates an instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the window 
.br
\fIwidht\fP The width of the window 
.br
\fIheight\fP The height of the window 
.RE
.PP

.PP
Definition at line 63 of file Scene\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void OpenGLAssignment::Scene::input ()\fC [inline]\fP"

.PP
Handle the input\&. 
.PP
Definition at line 160 of file Scene\&.hpp\&.
.SS "void OpenGLAssignment::Scene::render ()\fC [inline]\fP"

.PP
Render the scene\&. 
.PP
Definition at line 152 of file Scene\&.hpp\&.
.SS "void OpenGLAssignment::Scene::run ()\fC [inline]\fP"

.PP
\fBScene\fP loop\&. 
.PP
Definition at line 107 of file Scene\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Jesús Fermín Villar Ramírez | OpenGLAssignment from the source code\&.
