.TH "OpenGLAssignment::ColorRGBA8888::Data" 3 "Sun May 24 2020" "Jesús Fermín Villar Ramírez | OpenGLAssignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenGLAssignment::ColorRGBA8888::Data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ColorRGBA8888\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBr\fP"
.br
.ti -1c
.RI "   uint8_t \fBg\fP"
.br
.ti -1c
.RI "   uint8_t \fBb\fP"
.br
.ti -1c
.RI "   uint8_t \fBa\fP"
.br
.ti -1c
.RI "} \fBcomponent\fP"
.br
.ti -1c
.RI "uint32_t \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file ColorRGBA8888\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t OpenGLAssignment::ColorRGBA8888::Data::a"

.PP
Definition at line 46 of file ColorRGBA8888\&.hpp\&.
.SS "uint8_t OpenGLAssignment::ColorRGBA8888::Data::b"

.PP
Definition at line 45 of file ColorRGBA8888\&.hpp\&.
.SS "struct { \&.\&.\&. }  OpenGLAssignment::ColorRGBA8888::Data::component"

.SS "uint8_t OpenGLAssignment::ColorRGBA8888::Data::g"

.PP
Definition at line 44 of file ColorRGBA8888\&.hpp\&.
.SS "uint8_t OpenGLAssignment::ColorRGBA8888::Data::r"

.PP
Definition at line 43 of file ColorRGBA8888\&.hpp\&.
.SS "uint32_t OpenGLAssignment::ColorRGBA8888::Data::value"

.PP
Definition at line 49 of file ColorRGBA8888\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Jesús Fermín Villar Ramírez | OpenGLAssignment from the source code\&.
