.TH "OpenGLAssignment::ColorRGBA8888" 3 "Sun May 24 2020" "Jesús Fermín Villar Ramírez | OpenGLAssignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenGLAssignment::ColorRGBA8888
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ColorRGBA8888\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset\fP (int r, int g, int b, int a=255)"
.br
.RI "sets the colors components "
.ti -1c
.RI "\fBColorRGBA8888\fP & \fBoperator=\fP (const int &value)"
.br
.RI "Overloading operator to assign values\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBData\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file ColorRGBA8888\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBColorRGBA8888\fP& OpenGLAssignment::ColorRGBA8888::operator= (const int & value)\fC [inline]\fP"

.PP
Overloading operator to assign values\&. 
.PP
Definition at line 73 of file ColorRGBA8888\&.hpp\&.
.SS "void OpenGLAssignment::ColorRGBA8888::set (int r, int g, int b, int a = \fC255\fP)\fC [inline]\fP"

.PP
sets the colors components 
.PP
\fBParameters\fP
.RS 4
\fIr\fP The r component 
.br
\fIg\fP The g component 
.br
\fIb\fP The b component 
.br
\fIa\fP The a component 
.RE
.PP

.PP
Definition at line 62 of file ColorRGBA8888\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBData\fP OpenGLAssignment::ColorRGBA8888::data"

.PP
Definition at line 53 of file ColorRGBA8888\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Jesús Fermín Villar Ramírez | OpenGLAssignment from the source code\&.
